theme = 'jugo'
title = 'Jordan Herzstein'
sectionPagesMenu = 'main'
enableGitInfo = true
[params]
  [params.author]
    name = "Jordan Herzstein"
[markup.goldmark.renderer]
   unsafe = true
[taxonomies]
  category = 'categories'
  tags = 'tags'
  author = 'author'
[module]
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/feather'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/simple-icons'